CREATE DATABASE IF NOT EXISTS drive CHARSET utf8mb4;

USE drive;

CREATE TABLE IF NOT EXISTS abonnement(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nom VARCHAR(50) NOT NULL,
prix DECIMAL(5,2) NOT NULL,
stockage BIGINT NOT NULL)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS utilisateur(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nom VARCHAR(50) NOT NULL,
prenom VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
mdp VARCHAR(255) NOT NULL,
date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
id_abonnement INT NOT NULL,
CONSTRAINT fk_to_souscrire_abonnement
FOREIGN KEY(id_abonnement)
REFERENCES abonnement(id) ON DELETE RESTRICT)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dossier(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nom VARCHAR(50) NOT NULL,
date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
id_utilisateur INT NOT NULL,
CONSTRAINT fk_to_creer_utilisateur
FOREIGN KEY(id_utilisateur)
REFERENCES utilisateur(id) ON DELETE CASCADE,
id_dossier_parent INT,
CONSTRAINT fk_to_contenir_dossier_parent
FOREIGN KEY(id_dossier_parent)
REFERENCES dossier(id) ON DELETE CASCADE)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS fichier(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nom VARCHAR(50) NOT NULL,
extension VARCHAR(50) NOT NULL,
taille BIGINT NOT NULL,
url VARCHAR(255) NOT NULL,
`date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
id_utilisateur INT NOT NULL,
CONSTRAINT fk_to_posseder_utilisateur
FOREIGN KEY(id_utilisateur)
REFERENCES utilisateur(id) ON DELETE CASCADE,
id_dossier INT,
CONSTRAINT fk_to_classer_dossier
FOREIGN KEY(id_dossier)
REFERENCES dossier(id) ON DELETE CASCADE)ENGINE=InnoDB;



